document.write('<div id="mySidenav" class="sidenav">');
document.write('<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>');
document.write('<a href="home.htm">Home</a>');
document.write('<a href="myblog.htm">Blog</a>');
document.write('<a href="stuff.htm">Downloads</a>');
document.write('<a href="extras.htm">Extras</a>');
document.write('<a href="http://mebi.neocities.org">Mebi Studios</a>');
document.write('<a href="https://discord.gg/GpnED8V">Discord</a>');
document.write('<a href="guestbook.htm">Guestbook</a>');
document.write('<a href="https://neocities.org/site/coolman">Contact</a>');
document.write('</div>');